/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AppShell, type Athlete } from "./app-shell";

type View = "today"|"plan"|"progress"|"athlete"|"workout";
type ApiEnvelope = {ok:boolean;data?:any;error?:{code:string;message:string;details?:unknown}};
const idk=(name:string)=>`${name}:${crypto.randomUUID()}`;
const today=()=>new Date().toISOString().slice(0,10);
const monday=(value=new Date())=>{const d=new Date(value);const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()-day+1);return d.toISOString().slice(0,10)};
const plusDays=(date:string,days:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)};

async function action(operation:Record<string,unknown>):Promise<any>{
 const response=await fetch("/api/v1/action",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(operation)});
 const body=await response.json() as ApiEnvelope;
 if(!body.ok) throw Object.assign(new Error(body.error?.message??"Coach operation failed"),{code:body.error?.code});
 return body.data;
}

export function CoachApp({view}:{view:View}){
 const [athletes,setAthletes]=useState<Athlete[]>([]); const [athleteId,setAthleteId]=useState("");
 const [data,setData]=useState<any>(null); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 const [weekStart,setWeekStart]=useState(monday()); const [selectedDate,setSelectedDate]=useState(today());
 const router=useRouter(); const params=useSearchParams();
 const loadAthletes=useCallback(async()=>{try{const list=await action({operation:"listAthletes"}) as Athlete[];setAthletes(list);const saved=localStorage.getItem("coach-athlete");const next=list.some(a=>a.id===saved)?saved:(list[0]?.id??"");setAthleteId(current=>current&&list.some(a=>a.id===current)?current:next??"");}catch(e){setError((e as Error).message)}},[]);
 const load=useCallback(async()=>{
  if(!athleteId){setData(null);return} setError("");
  try{
   if(view==="athlete")setData(await action({operation:"getAthleteContext",athleteId}));
   if(view==="plan")setData(await action({operation:"getPlan",athleteId,weekStart}).catch((e:any)=>e.code==="NOT_FOUND"?null:Promise.reject(e)));
   if(view==="today")setData(await action({operation:"getToday",athleteId,date:selectedDate}));
   if(view==="progress")setData(await action({operation:"getProgress",athleteId,periodStart:plusDays(weekStart,-28),periodEnd:plusDays(weekStart,6)}));
   if(view==="workout"){
    const planId=params.get("planId");const sessionKey=params.get("sessionKey");if(!planId||!sessionKey)throw new Error("Workout link is incomplete");
    const plan=await action({operation:"getPlan",athleteId,planId});let workout=plan.workouts.find((w:any)=>w.sessionKey===sessionKey);
    if(!workout)workout=await action({operation:"startWorkout",athleteId,planId,sessionKey,expectedPlanVersion:plan.plan.version,idempotencyKey:idk("start-workout")});
    const session=plan.current.payload.sessions.find((s:any)=>s.key===sessionKey);setData({plan,session,workout});
   }
  }catch(e){setError((e as Error).message)}
 },[athleteId,params,selectedDate,view,weekStart]);
 useEffect(()=>{void loadAthletes()},[loadAthletes]);
 useEffect(()=>{if(athleteId){localStorage.setItem("coach-athlete",athleteId);void load()}},[athleteId,load]);
 async function run(work:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await work();setMessage(success);await load();await loadAthletes()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const selected=athletes.find(a=>a.id===athleteId);
 return <AppShell athletes={athletes} athleteId={athleteId} onAthlete={id=>{setAthleteId(id);setData(null);setMessage("")}}>
  {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}
  {view==="athlete"&&<AthleteView data={data} athleteId={athleteId} busy={busy} run={run}/>} 
  {view==="plan"&&<PlanView data={data} athleteId={athleteId} weekStart={weekStart} setWeekStart={setWeekStart} busy={busy} run={run}/>} 
  {view==="today"&&<TodayView data={data} athlete={selected} date={selectedDate} setDate={setSelectedDate} router={router}/>} 
  {view==="workout"&&<WorkoutView data={data} athleteId={athleteId} busy={busy} run={run} router={router}/>} 
  {view==="progress"&&<ProgressView data={data} athleteId={athleteId} weekStart={weekStart} setWeekStart={setWeekStart} busy={busy} run={run}/>} 
 </AppShell>
}

type Run=(work:()=>Promise<unknown>,message:string)=>Promise<void>;
function Field({label,name,type="text",defaultValue,required=true,children}:{label:string;name:string;type?:string;defaultValue?:string|number;required?:boolean;placeholder?:string;children?:React.ReactNode}){return <div className="field"><label htmlFor={name}>{label}</label>{children??<input id={name} name={name} type={type} defaultValue={defaultValue} required={required}/>}</div>}
function Submit({busy,children}:{busy:boolean;children:React.ReactNode}){return <button className="button" disabled={busy}>{busy?"Saving…":children}</button>}
function formData(event:FormEvent<HTMLFormElement>){event.preventDefault();return new FormData(event.currentTarget)}

function AthleteView({data,athleteId,busy,run}:{data:any;athleteId:string;busy:boolean;run:Run}){
 const entries:any[]=data?.entries??[];const goals=entries.filter(e=>e.kind==="goal");
 async function create(e:FormEvent<HTMLFormElement>){const f=formData(e);await run(()=>action({operation:"createAthlete",name:f.get("name"),displayName:f.get("name"),timezone:f.get("timezone"),idempotencyKey:idk("create-athlete")}),"Athlete created. Select them above to continue.")}
 async function persona(e:FormEvent<HTMLFormElement>){const f=formData(e);await run(()=>action({operation:"upsertPersona",athleteId,persona:{coachName:f.get("coachName"),styleBrief:f.get("styleBrief"),warmth:f.get("warmth"),explanation:f.get("explanation"),challenge:f.get("challenge")},idempotencyKey:idk("persona")}),"Coach persona saved")}
 async function addContext(kind:string,e:FormEvent<HTMLFormElement>){const f=formData(e);let payload:any;
  if(kind==="priority")payload={area:f.get("area"),level:f.get("level"),note:f.get("note")||undefined};
  if(kind==="preference")payload={text:f.get("text")};
  if(kind==="goal")payload={title:f.get("title"),description:f.get("description"),type:f.get("type"),priority:f.get("priority"),status:"active",baseline:f.get("baseline")||undefined,targetValue:f.get("targetValue")?Number(f.get("targetValue")):undefined,targetUnit:f.get("targetUnit")||undefined,qualitativeTarget:f.get("qualitativeTarget")||undefined,targetDate:f.get("targetDate")||undefined,indicators:String(f.get("indicators")||"").split(",").map(x=>x.trim()).filter(Boolean)};
  if(kind==="event")payload={name:f.get("name"),type:f.get("type"),date:f.get("date"),details:f.get("details")||undefined,targetOutcome:f.get("targetOutcome")||undefined,linkedGoalIds:f.get("goalId")?[f.get("goalId")]:[]};
  if(kind==="location")payload={name:f.get("name"),kind:f.get("type"),temporary:f.get("temporary")==="on",equipment:String(f.get("equipment")||"").split(",").map(x=>x.trim()).filter(Boolean).map(name=>({name,type:"other",attributes:{}}))};
  await run(()=>action({operation:"addContext",athleteId,kind,data:payload,idempotencyKey:idk(`add-${kind}`)}),`${kind[0].toUpperCase()+kind.slice(1)} saved`)
 }
 async function defineMetric(e:FormEvent<HTMLFormElement>){const f=formData(e);await run(()=>action({operation:"defineMetric",athleteId,definition:{key:f.get("key"),displayName:f.get("displayName"),unit:f.get("unit")},idempotencyKey:idk("define-metric")}),"Metric added")}
 async function recordMetric(e:FormEvent<HTMLFormElement>){const f=formData(e);await run(()=>action({operation:"recordMetric",athleteId,reading:{definitionId:f.get("definitionId"),measuredAt:new Date(String(f.get("date"))).toISOString(),value:Number(f.get("value")),source:{kind:"manual",label:"Coach app"}},idempotencyKey:idk("record-metric")}),"Metric reading recorded")}
 const personaEntry=entries.find(e=>e.kind==="persona");
 return <><section className="hero"><div><p className="eyebrow">Athlete</p><h1>{data?.athlete?.displayName??"Who is Coach training?"}</h1><p>Keep the durable context your Coach should remember. Short-lived constraints belong in weekly planning.</p></div>{data?.athlete&&<div className="card accent"><span className="eyebrow" style={{color:"#d8ee75"}}>Your trainer</span><h2 style={{marginTop:8}}>Coach {personaEntry?.data?.coachName??"unnamed"}</h2><p className="muted">{personaEntry?.data?.styleBrief??"Choose a name and coaching style below."}</p></div>}</section>
 <div className="grid"><section className="card"><h2>Add an athlete</h2><form onSubmit={create}><Field label="Athlete name" name="name"/><Field label="Timezone" name="timezone" defaultValue="Europe/London"/><Submit busy={busy}>Create athlete</Submit></form></section>
 {!athleteId?<section className="card"><h2>Select an athlete</h2><p className="muted">Create an athlete, then choose them from the selector above.</p></section>:<>
 <section className="card"><h2>Coach persona</h2><form onSubmit={persona}><Field label="Coach forename" name="coachName" defaultValue={personaEntry?.data?.coachName}/><Field label="Style brief" name="styleBrief"><textarea id="styleBrief" name="styleBrief" defaultValue={personaEntry?.data?.styleBrief??"Warm, direct and grounded. Explain the reason for important choices."}/></Field><div className="grid"><Field label="Warmth" name="warmth"><select name="warmth" id="warmth"><option value="balanced">Balanced</option><option value="high">High</option><option value="low">Low</option></select></Field><Field label="Explanation" name="explanation"><select name="explanation" id="explanation"><option value="balanced">Balanced</option><option value="concise">Concise</option><option value="detailed">Detailed</option></select></Field><Field label="Challenge" name="challenge"><select name="challenge" id="challenge"><option value="balanced">Balanced</option><option value="challenging">Challenging</option><option value="restrained">Restrained</option></select></Field></div><Submit busy={busy}>Save persona</Submit></form></section>
 <section className="card"><h2>Training priorities</h2><EntryList entries={entries.filter(e=>e.kind==="priority")}/><form onSubmit={e=>addContext("priority",e)}><Field label="Area" name="area"/><Field label="Emphasis" name="level"><select id="level" name="level"><option value="primary">Primary</option><option value="develop">Develop</option><option value="maintain">Maintain</option><option value="not_prioritised">Not currently prioritised</option></select></Field><Field label="Note" name="note" required={false}/><Submit busy={busy}>Add priority</Submit></form></section>
 <section className="card"><h2>Preferences</h2><EntryList entries={entries.filter(e=>e.kind==="preference")}/><form onSubmit={e=>addContext("preference",e)}><Field label="Explicit training preference" name="text"/><Submit busy={busy}>Add preference</Submit></form></section>
 <section className="card"><h2>Goals</h2><EntryList entries={goals}/><form onSubmit={e=>addContext("goal",e)}><Field label="Goal title" name="title"/><Field label="Description" name="description"><textarea id="description" name="description"/></Field><Field label="Goal type" name="type"><select id="type" name="type"><option value="performance">Performance</option><option value="physique">Physique</option><option value="health_fitness">Health / fitness</option><option value="body_composition">Body composition</option><option value="capability">Capability</option></select></Field><Field label="Priority" name="priority"><select id="priority" name="priority"><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></Field><Field label="Baseline (optional)" name="baseline" required={false}/><div className="grid"><Field label="Numeric target" name="targetValue" type="number" required={false}/><Field label="Unit" name="targetUnit" required={false}/></div><Field label="Qualitative target" name="qualitativeTarget" required={false}/><Field label="Target date" name="targetDate" type="date" required={false}/><Field label="Progress indicators, comma separated" name="indicators" required={false}/><Submit busy={busy}>Add goal</Submit></form></section>
 <section className="card"><h2>Events</h2><EntryList entries={entries.filter(e=>e.kind==="event")}/><form onSubmit={e=>addContext("event",e)}><Field label="Event name" name="name"/><Field label="Event type" name="type" defaultValue="Race"/><Field label="Date" name="date" type="date"/><Field label="Details" name="details" required={false}/><Field label="Target outcome" name="targetOutcome" required={false}/>{goals.length>0&&<Field label="Linked goal" name="goalId"><select id="goalId" name="goalId"><option value="">None</option>{goals.map(g=><option key={g.id} value={g.id}>{g.data.title}</option>)}</select></Field>}<Submit busy={busy}>Add event</Submit></form></section>
 <section className="card"><h2>Locations & equipment</h2><EntryList entries={entries.filter(e=>e.kind==="location")}/><form onSubmit={e=>addContext("location",e)}><Field label="Location name" name="name"/><Field label="Location type" name="type"><select id="type" name="type"><option value="home">Home</option><option value="gym">Gym</option><option value="outdoors">Outdoors</option><option value="travel">Travel</option><option value="other">Other</option></select></Field><Field label="Equipment, comma separated" name="equipment" required={false}/><label className="row"><input name="temporary" type="checkbox" style={{width:"auto"}}/> Temporary / travel location</label><br/><Submit busy={busy}>Add location</Submit></form></section>
 <section className="card"><h2>Tracked metrics</h2>{(data?.metrics??[]).map((m:any)=><div className="item" key={m.id}><strong>{m.displayName}</strong> <span className="pill">{m.unit}</span>{m.readings?.[0]&&<p><span className="metric">{m.readings[0].value}</span> {m.unit}<br/><small className="muted">{new Date(m.readings[0].measuredAt).toLocaleDateString()} · {m.readings[0].source}</small></p>}</div>)}<details><summary>Add metric definition</summary><form onSubmit={defineMetric}><Field label="Key, e.g. body_weight" name="key"/><Field label="Display name" name="displayName"/><Field label="Unit" name="unit"/><Submit busy={busy}>Add metric</Submit></form></details>{data?.metrics?.length>0&&<details><summary>Record a reading</summary><form onSubmit={recordMetric}><Field label="Metric" name="definitionId"><select id="definitionId" name="definitionId">{data.metrics.map((m:any)=><option key={m.id} value={m.id}>{m.displayName} ({m.unit})</option>)}</select></Field><Field label="Value" name="value" type="number"/><Field label="Date" name="date" type="date" defaultValue={today()}/><Submit busy={busy}>Record reading</Submit></form></details>}</section>
 </>}</div></>
}

function EntryList({entries}:{entries:any[]}){return <div className="list">{entries.map(entry=><div key={entry.id} className="item"><strong>{entry.data.title??entry.data.area??entry.data.name??entry.data.text}</strong>{entry.data.level&&<> <span className="pill">{String(entry.data.level).replaceAll("_"," ")}</span></>}<p className="muted">{entry.data.description??entry.data.qualitativeTarget??entry.data.note??entry.data.details}{entry.data.equipment?.length?` · ${entry.data.equipment.map((x:any)=>x.name).join(", ")}`:""}</p></div>)}</div>}

function PlanView({data,athleteId,weekStart,setWeekStart,busy,run}:{data:any;athleteId:string;weekStart:string;setWeekStart:(v:string)=>void;busy:boolean;run:Run}){
 async function weekly(e:FormEvent<HTMLFormElement>){const f=formData(e);const kind=String(f.get("kind"));const date=String(f.get("date"));await run(()=>action({operation:"setWeeklyContext",athleteId,entry:{kind,weekStart,effectiveFrom:date,effectiveTo:kind==="temporary"?String(f.get("to")):date,data:{date,durationMinutes:f.get("duration")?Number(f.get("duration")):undefined,window:f.get("window")||undefined,title:f.get("title")||undefined,note:f.get("note")||undefined}},idempotencyKey:idk("weekly-context")}),"Weekly context saved")}
 async function draft(e:FormEvent<HTMLFormElement>){const f=formData(e);const modality=String(f.get("modality"));const common={key:`${modality}-${String(f.get("date"))}`,date:f.get("date"),title:f.get("title"),intendedStimulus:f.get("stimulus"),durationMinutes:Number(f.get("duration")),coachCue:f.get("cue")||undefined,rationale:f.get("sessionRationale")||undefined};let session:any;
  if(modality==="strength")session={...common,modality,prescription:{exercises:[{exerciseName:f.get("exercise")||"Dumbbell bench press",cue:"Controlled reps with a stable shoulder position",sets:[{reps:Number(f.get("reps")||10),load:Number(f.get("load")||0),unit:"kg",restSeconds:90},{reps:Number(f.get("reps")||10),load:Number(f.get("load")||0),unit:"kg",restSeconds:90},{reps:Number(f.get("reps")||10),load:Number(f.get("load")||0),unit:"kg",restSeconds:90}]}]}};
  if(modality==="run")session={...common,modality,prescription:{durationMinutes:Number(f.get("duration")),intensity:f.get("intensity")||"Easy conversational effort"}};
  if(modality==="cycle")session={...common,modality,prescription:{durationMinutes:Number(f.get("duration")),intensity:f.get("intensity")||"Steady aerobic",zwiftWorkout:f.get("zwift")||undefined}};
  await run(()=>action({operation:"createDraftPlan",athleteId,weekStart,plan:{rationale:f.get("planRationale"),sessions:[session]},idempotencyKey:idk("draft-plan")}),"Draft week created")
 }
 async function lock(){await run(()=>action({operation:"lockPlan",athleteId,planId:data.plan.id,expectedVersion:data.plan.version,confirmation:"lock",idempotencyKey:idk("lock-plan")}),"Week locked. This version is now the accepted baseline.")}
 async function revise(e:FormEvent<HTMLFormElement>){const f=formData(e);await run(()=>action({operation:"reviseDraftPlan",athleteId,planId:data.plan.id,expectedVersion:data.plan.version,plan:{...data.current.payload,rationale:f.get("rationale")},idempotencyKey:idk("revise-plan")}),"Draft revised")}
 async function adapt(e:FormEvent<HTMLFormElement>){const f=formData(e);const sessions=data.current.payload.sessions.map((s:any,i:number)=>i===0?{...s,date:String(f.get("date"))}:s);await run(()=>action({operation:"adaptPlan",athleteId,planId:data.plan.id,expectedVersion:data.plan.version,reason:f.get("reason"),plan:{...data.current.payload,sessions},accepted:true,idempotencyKey:idk("adapt-plan")}),"Accepted adaptation saved; baseline preserved")}
 const plan=data?.plan;const current=data?.current?.payload;const adapted=plan?.baselineVersion&&plan.version!==plan.baselineVersion;
 return <><section className="hero"><div><p className="eyebrow">Plan</p><h1>Your week,<br/>agreed.</h1><p>Availability is an opportunity, not a quota. Coach can build fewer sessions than the time you offer.</p></div><div className="card"><Field label="Week starting" name="week"><input id="week" type="date" value={weekStart} onChange={e=>setWeekStart(e.target.value)}/></Field><button className="button secondary" onClick={()=>setWeekStart(monday(new Date(`${weekStart}T12:00:00Z`)))}>Use this Monday</button></div></section>
 {!athleteId?<p className="notice">Create or select an athlete first.</p>:<div className="grid"><section className="card"><h2>Real-life context</h2><form onSubmit={weekly}><Field label="Kind" name="kind"><select id="kind" name="kind"><option value="availability">Availability</option><option value="anchor">Fixed anchor</option><option value="temporary">Temporary context</option></select></Field><Field label="Date / start" name="date" type="date" defaultValue={weekStart}/><Field label="End date (for temporary context)" name="to" type="date" defaultValue={plusDays(weekStart,6)} required={false}/><Field label="Available duration (minutes)" name="duration" type="number" required={false}/><Field label="Window" name="window" placeholder={undefined} required={false}/><Field label="Title" name="title" required={false}/><Field label="Context or constraint" name="note" required={false}/><Submit busy={busy}>Save context</Submit></form></section>
 {!plan?<section className="card"><h2>Create a structured draft</h2><p className="muted">This app form exercises the same trusted service operation used by the Custom GPT.</p><form onSubmit={draft}><Field label="Plan rationale" name="planRationale" defaultValue="A realistic week shaped around the athlete's priorities and available recovery."/><Field label="Session date" name="date" type="date" defaultValue={weekStart}/><Field label="Modality" name="modality"><select id="modality" name="modality"><option value="strength">Strength</option><option value="run">Run</option><option value="cycle">Cycle</option></select></Field><Field label="Session title" name="title" defaultValue="Primary training session"/><Field label="Intended stimulus" name="stimulus" defaultValue="Progress the primary goal with recoverable work"/><Field label="Duration (minutes)" name="duration" type="number" defaultValue={45}/><Field label="Coach cue" name="cue" required={false}/><Field label="Session rationale" name="sessionRationale" required={false}/><Field label="Strength exercise" name="exercise" defaultValue="Dumbbell bench press" required={false}/><div className="grid"><Field label="Target reps" name="reps" type="number" defaultValue={10} required={false}/><Field label="Load (kg)" name="load" type="number" defaultValue={12} required={false}/></div><Field label="Run/cycle intensity" name="intensity" required={false}/><Field label="Named Zwift workout" name="zwift" required={false}/><Submit busy={busy}>Create draft week</Submit></form></section>:<section className="card" style={{gridColumn:"1 / -1"}}><div className="spread"><div><span className="pill">{plan.status}</span>{adapted&&<span className="pill adapted">adapted</span>}<h2 style={{marginTop:10}}>Week of {plan.weekStart}</h2><p className="muted">Version {plan.version}{plan.baselineVersion?` · accepted baseline v${plan.baselineVersion}`:""}</p></div>{plan.status==="draft"&&<button className="button" onClick={lock} disabled={busy}>Lock week</button>}</div><p>{current.rationale}</p><div className="grid">{current.sessions.map((s:any)=><SessionCard key={s.key} session={s} plan={plan}/>)}</div>{plan.status==="draft"&&<form onSubmit={revise}><Field label="Revise plan rationale" name="rationale" defaultValue={current.rationale}/><Submit busy={busy}>Save revision</Submit></form>}{plan.status==="locked"&&<details><summary>Adapt accepted week</summary><form onSubmit={adapt}><Field label="Reason for change" name="reason"/><Field label="Move first session to" name="date" type="date" defaultValue={current.sessions[0]?.date}/><Submit busy={busy}>Accept adaptation</Submit></form></details>}{data.baseline&&<details><summary>Accepted baseline</summary><pre>{JSON.stringify(data.baseline.payload,null,2)}</pre></details>}</section>}</div>}</>
}

function SessionCard({session,plan}:{session:any;plan:any}){return <article className="card session"><div className="spread"><span className="pill">{session.modality}</span><small className="muted">{session.durationMinutes} min</small></div><h3 style={{marginTop:12}}>{session.title}</h3><p><strong>{session.intendedStimulus}</strong></p><p className="muted">{session.coachCue}</p><details><summary>Prescription</summary><pre>{JSON.stringify(session.prescription,null,2)}</pre></details>{plan.status==="locked"&&<a className="button secondary" style={{marginTop:12}} href={`/workout?planId=${plan.id}&sessionKey=${encodeURIComponent(session.key)}`}>Start / resume</a>}</article>}

function TodayView({data,athlete,date,setDate,router}:{data:any;athlete?:Athlete;date:string;setDate:(v:string)=>void;router:ReturnType<typeof useRouter>}){
 const session=data?.session;return <><section className="hero"><div><p className="eyebrow">Today · {athlete?.displayName??"No athlete selected"}</p><h1>{session?session.title:"A day with space."}</h1><p>{session?.intendedStimulus??data?.missing??"Select an athlete to see today's training."}</p></div><div className="card"><Field label="View date" name="today-date"><input id="today-date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field></div></section>{session&&<section className="card accent"><div className="spread"><span className="pill">{session.modality}</span>{data.adapted&&<span className="pill adapted">adapted from baseline</span>}</div><h2 style={{marginTop:18}}>{session.durationMinutes} minutes · {session.intendedStimulus}</h2><p className="muted">{session.coachCue??session.rationale}</p><details><summary>Full prescription</summary><pre>{JSON.stringify(session.prescription,null,2)}</pre></details><button className="button" style={{background:"#d8ee75",color:"#174f3d",marginTop:18}} onClick={()=>router.push(`/workout?planId=${data.plan.id}&sessionKey=${encodeURIComponent(session.key)}`)}>{data.workout?.status==="in_progress"?"Resume workout":"Start workout"}</button>{data.workout&&<p><small>Status: {data.workout.status.replaceAll("_"," ")}</small></p>}</section>}</>
}

function WorkoutView({data,athleteId,busy,run,router}:{data:any;athleteId:string;busy:boolean;run:Run;router:ReturnType<typeof useRouter>}){
 const [timer,setTimer]=useState(0);useEffect(()=>{if(timer<=0)return;const t=setInterval(()=>setTimer(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[timer]);
 const workout=data?.workout;const session=data?.session;
 async function logSet(e:FormEvent<HTMLFormElement>){const f=formData(e);await run(()=>action({operation:"logSet",athleteId,workoutId:workout.id,expectedVersion:workout.version,exerciseName:f.get("exerciseName"),setIndex:Number(f.get("setIndex")),reps:f.get("reps")?Number(f.get("reps")):undefined,load:f.get("load")?Number(f.get("load")):undefined,unit:"kg",idempotencyKey:idk("log-set")}),"Set logged");setTimer(Number(f.get("rest")||0))}
 async function complete(e:FormEvent<HTMLFormElement>){const f=formData(e);const evidence=f.get("evidenceDescription")?{source:{kind:"athlete_evidence",label:String(f.get("evidenceLabel")||"Athlete-provided screenshot/file"),confidence:f.get("confidence")||undefined},description:f.get("evidenceDescription"),fields:String(f.get("evidenceFields")||"").split(",").map(x=>x.trim()).filter(Boolean),retainedRaw:false}:undefined;await run(()=>action({operation:"completeWorkout",athleteId,workoutId:workout.id,expectedVersion:workout.version,outcome:f.get("outcome"),actual:{durationMinutes:f.get("duration")?Number(f.get("duration")):undefined,distanceKm:f.get("distance")?Number(f.get("distance")):undefined,pace:f.get("pace")||undefined,averageHeartRate:f.get("hr")?Number(f.get("hr")):undefined,averagePower:f.get("power")?Number(f.get("power")):undefined,result:f.get("result")||undefined,source:{kind:f.get("source"),label:f.get("sourceLabel")||"Coach app"}},feedback:f.get("difficulty")?{difficulty:f.get("difficulty"),note:f.get("feedback")||undefined}:undefined,evidence:evidence?[evidence]:[],coachInterpretation:f.get("interpretation")||undefined,idempotencyKey:idk("complete-workout")}),"Workout saved")}
 if(!session||!workout)return <p className="notice">Opening workout…</p>;
 if(["completed","partial","skipped","missed"].includes(workout.status))return <><p className="eyebrow">Workout saved</p><h1>{session.title}</h1><section className="card"><span className="pill">{workout.status}</span><h2>Prescription and reality are preserved</h2><p className="muted">The accepted prescription, effective prescription, actual result, feedback and Coach interpretation remain separately queryable.</p><button className="button" onClick={()=>router.push("/progress")}>View progress</button></section></>;
 const exercise=session.modality==="strength"?session.prescription.exercises[0]:null;
 return <><section className="hero"><div><p className="eyebrow">Active workout · {session.modality}</p><h1>{session.title}</h1><p>{session.intendedStimulus}</p></div><div className="card accent"><p className="eyebrow" style={{color:"#d8ee75"}}>Rest timer</p><div className="timer">{Math.floor(timer/60)}:{String(timer%60).padStart(2,"0")}</div><div className="row"><button className="button secondary" onClick={()=>setTimer(60)}>1:00</button><button className="button secondary" onClick={()=>setTimer(90)}>1:30</button><button className="button ghost" style={{color:"white"}} onClick={()=>setTimer(0)}>Clear</button></div></div></section>
 <div className="grid">{exercise&&<section className="card"><h2>{exercise.exerciseName}</h2><p className="muted">{exercise.cue}</p><div className="list">{exercise.sets.map((s:any,i:number)=><div className="item" key={i}>Set {i+1}: <strong>{s.reps} reps{s.load!==undefined?` · ${s.load} ${s.unit??""}`:""}</strong> · {s.restSeconds??0}s rest</div>)}</div><form onSubmit={logSet}><input type="hidden" name="exerciseName" value={exercise.exerciseName}/><Field label="Set number" name="setIndex" type="number" defaultValue={1}/><div className="grid"><Field label="Actual reps" name="reps" type="number"/><Field label="Actual load" name="load" type="number"/></div><Field label="Start rest timer (seconds)" name="rest" type="number" defaultValue={exercise.sets[0]?.restSeconds??90}/><Submit busy={busy}>Log set</Submit></form></section>}
 <section className="card"><h2>Complete or close session</h2><form onSubmit={complete}><Field label="Outcome" name="outcome"><select id="outcome" name="outcome"><option value="completed">Completed</option><option value="partial">Partially completed</option><option value="skipped">Deliberately skipped</option><option value="missed">Missed</option></select></Field><Field label="Actual duration (minutes)" name="duration" type="number" defaultValue={session.durationMinutes} required={false}/>{session.modality==="run"&&<><Field label="Distance (km)" name="distance" type="number" required={false}/><Field label="Pace" name="pace" required={false}/><Field label="Average heart rate" name="hr" type="number" required={false}/></>}{session.modality==="cycle"&&<><Field label="Average power (W)" name="power" type="number" required={false}/><Field label="Average heart rate" name="hr" type="number" required={false}/></>}<Field label="Result note" name="result" required={false}/><Field label="Actual source" name="source"><select id="source" name="source"><option value="manual">Entered directly</option><option value="conversation">Logged conversationally</option><option value="athlete_evidence">Extracted from athlete evidence</option></select></Field><Field label="Source label" name="sourceLabel" defaultValue="Coach app"/><Field label="Difficulty" name="difficulty"><select id="difficulty" name="difficulty"><option value="about_right">About right</option><option value="easy">Easy</option><option value="hard">Hard</option><option value="very_hard">Very hard</option></select></Field><Field label="Athlete feedback" name="feedback" required={false}/><details><summary>Athlete-provided evidence provenance</summary><Field label="Evidence label" name="evidenceLabel" required={false}/><Field label="What the GPT could inspect" name="evidenceDescription" required={false}/><Field label="Fields extracted, comma separated" name="evidenceFields" required={false}/><Field label="Extraction confidence" name="confidence"><select id="confidence" name="confidence"><option value="">Not stated</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></Field></details><Field label="Coach interpretation (clearly labelled)" name="interpretation" required={false}/><Submit busy={busy}>Save workout</Submit></form></section></div></>
}

function ProgressView({data,athleteId,weekStart,setWeekStart,busy,run}:{data:any;athleteId:string;weekStart:string;setWeekStart:(v:string)=>void;busy:boolean;run:Run}){
 const summary=data?.factualSummary;const goals=(data?.goalsAndEvents??[]).filter((x:any)=>x.kind==="goal");const latest=data?.coachReviews?.[0];
 async function review(e:FormEvent<HTMLFormElement>){const f=formData(e);const assessments=goals.length?[{goalId:goals[0].id,status:f.get("goalStatus"),summary:f.get("goalSummary")||"Assessment based on the period evidence."}]:[];await run(()=>action({operation:"createReview",athleteId,periodStart:plusDays(weekStart,-7),periodEnd:plusDays(weekStart,-1),summary:f.get("summary"),goalAssessments:assessments,recommendedDirection:f.get("direction"),evidenceRefs:String(f.get("evidenceRefs")||"").split(",").map(x=>x.trim()).filter(Boolean),idempotencyKey:idk("review")}),"Coach review saved and available to next-week planning")}
 return <><section className="hero"><div><p className="eyebrow">Progress</p><h1>{latest?.summary??(data?.evidenceSufficient?"The evidence is building.":"Start with evidence.")}</h1><p>{latest?.recommendedDirection??"Coach separates factual training evidence from athlete feedback and coaching interpretation."}</p></div><div className="card"><Field label="Review through week starting" name="progress-week"><input id="progress-week" type="date" value={weekStart} onChange={e=>setWeekStart(e.target.value)}/></Field></div></section>
 {summary&&<div className="grid"><section className="card accent"><p className="eyebrow" style={{color:"#d8ee75"}}>Planned versus actual</p><div className="metric">{summary.completed} / {summary.planned}</div><p className="muted">sessions completed · {summary.partial} partial · {summary.skipped} skipped · {summary.missed} missed</p></section><section className="card"><h2>Active goals</h2><EntryList entries={goals}/>{goals.length===0&&<p className="muted">No active goal evidence yet.</p>}</section><section className="card"><h2>Relevant history</h2>{data.modality.map((m:any)=><div className="item" key={m.kind}><strong style={{textTransform:"capitalize"}}>{m.kind}</strong><p className="muted">{m.workouts.length} recorded workout{m.workouts.length===1?"":"s"}</p></div>)}</section><section className="card"><h2>Metric evidence</h2><p className="metric">{data.metrics.length}</p><p className="muted">tracked readings in this period</p></section><section className="card" style={{gridColumn:"1 / -1"}}><h2>Close the coaching loop</h2><p className="muted">Store concise evidence-linked conclusions. Do not paste hidden reasoning.</p><form onSubmit={review}><Field label="Coach assessment" name="summary"><textarea id="summary" name="summary" required/></Field>{goals.length>0&&<><Field label={`Assessment for ${goals[0].data.title}`} name="goalStatus"><select id="goalStatus" name="goalStatus"><option value="progressing_well">Progressing well</option><option value="progressing">Progressing</option><option value="unclear">Unclear / insufficient evidence</option><option value="stalled">Stalled</option><option value="needs_review">Needs review</option></select></Field><Field label="Goal assessment summary" name="goalSummary"/></>}<Field label="Recommended direction" name="direction"><textarea id="direction" name="direction" required/></Field><Field label="Evidence references, comma separated" name="evidenceRefs" required={false}/><Submit busy={busy}>Save review</Submit></form></section></div>}</>
}
